spring:
  application:
    name: transferencia
  kafka:
    producer:
      # Onde está o nosso "carteiro"?
      bootstrap-servers: localhost:9092

      # Como traduzir a mensagem de texto (String) para bytes antes de enviar pela rede
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer